#!/bin/sh
vcs -full64 -sverilog time -v ../rtl/Misc/lib1 ../rtl/Adders/base_adders.v ../rtl/Multipliers/dadda_unsigned_multiplier_RCA_16.v tests/multipliers/dadda_unsigned_multiplier_RCA_16_test.v -debug_all
./simv
