#!/bin/sh
vcs -full64 -sverilog time -v ../rtl/misc/lib1 ../rtl/multipliers/russian_peasant/russian_peasant_signed_multiplier_16.v tests/multipliers/russian_peasant_signed_multiplier_16_test.v -debug_all
./simv
