#!/bin/sh
vcs -full64 -sverilog time -v ../rtl/misc/lib1 ../rtl/multipliers/russian_peasant/russian_peasant_unsigned_multiplier_8.v tests/multipliers/russian_peasant_unsigned_multiplier_8_test.v -debug_all
./simv
