#!/bin/sh
module load synopsys/vcs
vcs -full64 -sverilog time -v ../rtl/Misc/lib1 ../rtl/Multipliers/russian_peasant_unsigned_multiplier.v tests/multipliers/russian_peasant_unsigned_multiplier_4_test.v -debug_all
./simv
