#!/bin/sh
vcs -full64 -sverilog time -v ../rtl/misc/lib1 ../rtl/multipliers/russian_peasant/russian_peasant_modified_unsigned_multiplier_4.v tests/multipliers/russian_peasant_modified_unsigned_multiplier_4_test.v -debug_all
./simv
