#!/bin/sh
module load synopsys/vcs
vcs -full64 -sverilog time -v ../rtl/Misc/lib1 ../rtl/Adders/base_adders.v ../rtl/Multipliers/wallace_signed_multiplier.v tests/multipliers/wallace_signed_multiplier_8_test.v -debug_all
./simv
